from . import tags
from . import fuel_types
from . import types
from . import flights
from . import drivers
from . import vehicles
from . import travels
from . import tickets
from . import passengers
